CREATE DATABASE ecommerce_sales_analysis;

SHOW databases;

USE ecommerce_sales_analysis;

SELECT * FROM customers;

SELECT * FROM orders;

SELECT * FROM order_items;

SELECT * FROM payments;

SELECT * FROM products;

SELECT * from sellers;

-- 1.) How many total orders were placed?
SELECT COUNT(order_id)
FROM orders;
-- There are total 99441 orders placed

-- 2.) How many unique customers are there?
SELECT COUNT(customer_unique_id)
FROM customers;

-- 3.) What is the total revenue generated?
SELECT ROUND(SUM(price),2) AS total_revenue
FROM order_items;
-- The Total revenue of orders is 13591643.7

-- 4.) Which state genrated the highest revenue?
SELECT 
      customers.customer_state,
      ROUND(SUM(order_items.price)) AS total_order_prices
FROM customers 
LEFT JOIN orders  ON customers.customer_id=orders.customer_id
LEFT JOIN order_items ON orders.order_id=order_items.order_id
GROUP BY  customers.customer_state
ORDER BY total_order_prices desc
LIMIT 1;
-- The SP state has the highest revenue of 5202955

-- 5.) Which product category generated the highest revenue?
 SELECT 
       products.product_category_name,
       ROUND(SUM(order_items.price)) AS total_product_revenue
FROM products
LEFT JOIN order_items ON products.product_id=order_items.product_id
GROUP BY products.product_category_name
ORDER BY total_product_revenue DESC
LIMIT 1; 
-- The higest product category is beleza_saude with revenue of 1258681

-- 6.)Which seller generated the highest revenue?
SELECT 
      sellers.seller_id,
      ROUND(SUM(order_items.price)) AS total_seller_revenue
FROM sellers
LEFT JOIN order_items ON sellers.seller_id=order_items.seller_id
GROUP BY sellers.seller_id
ORDER BY total_seller_revenue desc
LIMIT 1;
-- The seller_id 4869f7a5dfa277a7dca6462dcf3b52b2 has the highest revenue of 229473

-- 7.) What is the average value of the order?
 SELECT ROUND(SUM(price)/COUNT(DISTINCT order_id), 2) AS Avg_order_price
 FROM order_items;
 -- The average order would be 137.75 for every customer
 
 -- 8.) Show the top 10 sellers by revenue?
 SELECT 
      sellers.seller_id,
      ROUND(SUM(order_items.price)) AS total_seller_revenue
FROM sellers
LEFT JOIN order_items ON sellers.seller_id=order_items.seller_id
GROUP BY sellers.seller_id
ORDER BY total_seller_revenue desc
LIMIT 10;

-- 9.) Show the top 10 product categories by revenue ?
 SELECT 
       products.product_category_name,
       ROUND(SUM(order_items.price)) AS total_product_revenue
FROM products
LEFT JOIN order_items ON products.product_id=order_items.product_id
GROUP BY products.product_category_name
ORDER BY total_product_revenue DESC
LIMIT 10;

-- 10.) Which states placed the highest number of orders?
SELECT 
       customers.customer_state,
       COUNT(DISTINCT order_items.order_id) AS Number_Of_orders
FROM customers
LEFT JOIN orders ON customers.customer_id=orders.customer_id
LEFT JOIN order_items ON orders.order_id=order_items.order_id
GROUP BY customers.customer_state
ORDER BY Number_Of_orders DESC;
-- Most placed orders from state 'SP' with 41375

-- 11.) What is the average product price for each category?
SELECT 
      products.product_category_name,
      AVG(order_items.price) AS avg_prices
FROM products
LEFT JOIN order_items ON products.product_id=order_items.product_id
GROUP BY products.product_category_name
ORDER BY avg_prices desc; 

-- 12.) Sellers Peformances?
SELECT 
       seller_id,
       COUNT(order_id) AS total_orders,
       SUM(price) AS total_prices
FROM order_items
GROUP BY seller_id
ORDER BY total_prices DESC;

-- 13.) Show revenue generated by each state?
SELECT 
      customers.customer_state,
      ROUND(SUM(order_items.price)) AS total_state_revenue
FROM customers 
LEFT JOIN orders  ON customers.customer_id=orders.customer_id
LEFT JOIN order_items ON orders.order_id=order_items.order_id
GROUP BY  customers.customer_state
ORDER BY total_state_revenue desc;
-- List contains with SP with the highest, RR with the lowest

-- 14.) Which order generates the highest revenue?
SELECT order_id,
       ROUND(SUM(price)) AS order_prices
FROM order_items
GROUP BY order_id
ORDER BY order_prices DESC
LIMIT 1;

-- 15.) Customer Lifetime value?
SELECT 
      customers.customer_id,
      ROUND(SUM(payments.payment_value)) AS customer_spendings
FROM customers
LEFT JOIN orders ON customers.customer_id=orders.customer_id
LEFT JOIN payments ON orders.order_id=payments.order_id
GROUP BY customers.customer_id
ORDER BY customer_spendings DESC;

-- 16.) How does revenue change month by month?
SELECT 
      EXTRACT(month from orders.order_purchase_timestamp) AS months,
      ROUND(SUM(order_items.price)) AS order_prices
FROM orders
LEFT JOIN order_items ON orders.order_id=order_items.order_id
GROUP BY months
ORDER BY months asc;
-- First five months there is grudual increment and next three months the progress got down 6th to 11th there is a lot of improvement and atleast the 12th month it got down again by 30%
 
-- 17.) How many orders were placed each month?
SELECT 
      EXTRACT(month from orders.order_purchase_timestamp) AS months,
      COUNT(order_id) AS Number_Of_Orders
FROM orders
GROUP BY months
ORDER BY months asc;
    
-- 18.) what is the highest product category name in the highest revenue 
SELECT 
       products.product_category_name,       
       ROUND(SUM(order_items.price)) AS order_prices
FROM customers
LEFT JOIN orders ON customers.customer_id=orders.customer_id
LEFT JOIN order_items ON orders.order_id=order_items.order_id
LEFT JOIN products ON order_items.product_id=products.product_id
WHERE customers.customer_state='SP'
GROUP BY products.product_category_name
ORDER BY order_prices DESC
LIMIT 1;
-- it is cama_mesa_banho with total revenue 478285

-- 19.) What percentage of total revenue comes from each category?
SELECT 
      products.product_category_name,
     ROUND(SUM(order_items.price)*100/ 
(SELECT SUM(price) 
from order_items),2) AS revenue_percentage
FROM products
LEFT JOIN order_items ON products.product_id=order_items.product_id
GROUP BY products.product_category_name
ORDER BY revenue_percentage DESC;

--                                                     INSIGHTS
-- 1.)Who spends the most money?
SELECT 
       customers.customer_id,
       SUM(payments.payment_value) AS customer_payment_value
FROM customers
LEFT JOIN orders ON customers.customer_id=orders.customer_id
LEFT JOIN payments ON orders.order_id=payments.order_id
GROUP BY customers.customer_id
ORDER BY customer_payment_value DESC
LIMIT 10;
-- customer_id 1617b1357756262bfa56ab541c47bc16 spends around 13664.08 and was the highest on the chart to spends the most

-- 2.) Which categories drive the business?
SELECT 
      products.product_category_name,
      ROUND(SUM(order_items.price),2) AS category_price
FROM products
LEFT JOIN order_items ON products.product_id=order_items.product_id
GROUP BY products.product_category_name
ORDER BY category_price DESC
LIMIT 1;
-- beleza_saude is the product category which is sold out the most 

-- 3.) Is revenue increasing or decreasing?
SELECT 
      EXTRACT(month from orders.order_purchase_timestamp) AS months,
      ROUND(SUM(order_items.price)) AS monthly_prices
FROM orders
LEFT JOIN order_items ON orders.order_id=order_items.order_id
GROUP BY months
ORDER BY months ASC;

-- 4.) How many customers ordered more than once?
SELECT
      customer_id,
      COUNT(order_id) 
FROM orders
GROUP BY customer_id
HAVING COUNT(order_id) >1
ORDER BY customer_id DESC;

-- 5.) How many products does a customer buy per an order?
SELECT 
      product_id,
      COUNT(order_item_id) AS Number_Of_items_Per_Products
FROM order_items
GROUP BY product_id
ORDER BY Number_Of_items_Per_Products DESC
LIMIT 10;

-- 6.) Which sellers drive most revenue?
SELECT 
      sellers.seller_id,
      ROUND(sum(order_items.price)) AS seller_revenue
FROM sellers
LEFT JOIN order_items ON sellers.seller_id=order_items.seller_id
GROUP BY sellers.seller_id
ORDER BY seller_revenue desc
LIMIT 10;


-- 7.) Top category in each state?
WITH RankedCategories AS(SELECT 
       customers.customer_state,
       products.product_category_name,       
       ROUND(SUM(order_items.price)) AS order_prices,
       ROW_Number() OVER(PARTITION BY customers.customer_state
                 ORDER BY SUM(order_items.price) DESC ) AS category_rank
FROM customers
LEFT JOIN orders ON customers.customer_id=orders.customer_id
LEFT JOIN order_items ON orders.order_id=order_items.order_id
LEFT JOIN products ON order_items.product_id=products.product_id
GROUP BY customers.customer_state,
		products.product_category_name)

SELECT 
      customer_state,
      product_category_name,
      order_prices
FROM RankedCategories
WHERE category_rank =1
ORDER BY order_prices DESC;
--

-- 8.) Revenue contributed of each category?
SELECT 
      products.product_category_name,
      ROUND(SUM(order_items.price)*100/
(SELECT SUM(price) FROM order_items),2) AS revenue_percentage
FROM products
LEFT JOIN order_items ON products.product_id=order_items.product_id
GROUP BY products.product_category_name
ORDER BY revenue_percentage DESC;

-- 9.) Average order value by state?
SELECT 
      customers.customer_state,
	  AVG(order_totals.order_value) AS avg_order_value 
FROM customers
LEFT JOIN orders ON customers.customer_id=orders.customer_id
LEFT join 
(SELECT 
      order_id,
      SUM(price) AS order_value
FROM order_items
GROUP BY order_id) AS order_totals
ON orders.order_id=order_totals.order_id
GROUP BY customers.customer_state
ORDER BY avg_order_value  desc;
      
      